#ifndef __visualization_msgs__msg__InteractiveMarkerPose__idl__
#define __visualization_msgs__msg__InteractiveMarkerPose__idl__

#include "geometry_msgs/msg/./Pose_.idl"
#include "std_msgs/msg/./Header_.idl"
module visualization_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="visualization_msgs::msg::dds_::InteractiveMarkerPose_")
      struct InteractiveMarkerPose
      {
        /**
         * Time/frame info.
         */
        std_msgs::msg::dds::Header header;
        /**
         * Initial pose. Also, defines the pivot point for rotations.
         */
        geometry_msgs::msg::dds::Pose pose;
        /**
         * Identifying string. Must be globally unique in
         * the topic that this message is sent through.
         */
        string name;
      };  // struct InteractiveMarkerPose
    };  // module dds_
  };  // module msg
};  // module visualization_msgs

#endif  // __visualization_msgs__msg__InteractiveMarkerPose__idl__
