#ifndef __visualization_msgs__msg__MarkerArray__idl__
#define __visualization_msgs__msg__MarkerArray__idl__

#include "visualization_msgs/msg/./Marker_.idl"
module visualization_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="visualization_msgs::msg::dds_::MarkerArray_")
      struct MarkerArray
      {
        sequence<visualization_msgs::msg::dds::Marker> markers;
      };  // struct MarkerArray
    };  // module dds_
  };  // module msg
};  // module visualization_msgs

#endif  // __visualization_msgs__msg__MarkerArray__idl__
