#ifndef __rcl_interfaces__msg__IntraProcessMessage__idl__
#define __rcl_interfaces__msg__IntraProcessMessage__idl__

module rcl_interfaces
{
  module msg
  {
    module dds
    {

      @TypeCode(type="rcl_interfaces::msg::dds_::IntraProcessMessage_")
      struct IntraProcessMessage
      {
        unsigned long long publisher_id;
        unsigned long long message_sequence;
      };
    };
  };
};

#endif
