#ifndef __rcl_interfaces__msg__ParameterType__idl__
#define __rcl_interfaces__msg__ParameterType__idl__

module rcl_interfaces
{
  module msg
  {
    module dds
    {
      const octet PARAMETER_NOT_SET =
      0;

      const octet PARAMETER_BOOL =
      1;

      const octet PARAMETER_INTEGER =
      2;

      const octet PARAMETER_DOUBLE =
      3;

      const octet PARAMETER_STRING =
      4;

      const octet PARAMETER_BYTES =
      5;


      @TypeCode(type="rcl_interfaces::msg::dds_::ParameterType_")
      struct ParameterType
      {
        boolean unused_placeholder_field;
      };
    };
  };
};

#endif
