#ifndef __shape_msgs__msg__Plane__idl__
#define __shape_msgs__msg__Plane__idl__

module shape_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Representation of a plane, using the plane equation ax + by + cz + d = 0.
       */
      @TypeCode(type="shape_msgs::msg::dds_::Plane_")
      struct Plane
      {
        /**
         * a := coef[0]
         * b := coef[1]
         * c := coef[2]
         * d := coef[3]
         */
        double coef[4];
      };
    };
  };
};

#endif
