#ifndef __geometry_msgs__msg__PointStamped__idl__
#define __geometry_msgs__msg__PointStamped__idl__

#include "geometry_msgs/msg/./Point_.idl"
#include "std_msgs/msg/./Header_.idl"
module geometry_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This represents a Point with reference coordinate frame and timestamp
       */
      @TypeCode(type="geometry_msgs::msg::dds_::PointStamped_")
      struct PointStamped
      {
        std_msgs::msg::dds::Header header;
        geometry_msgs::msg::dds::Point point;
      };
    };
  };
};

#endif
