#ifndef __geometry_msgs__msg__PolygonStamped__idl__
#define __geometry_msgs__msg__PolygonStamped__idl__

#include "geometry_msgs/msg/./Polygon_.idl"
#include "std_msgs/msg/./Header_.idl"
module geometry_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This represents a Polygon with reference coordinate frame and timestamp
       */
      @TypeCode(type="geometry_msgs::msg::dds_::PolygonStamped_")
      struct PolygonStamped
      {
        std_msgs::msg::dds::Header header;
        geometry_msgs::msg::dds::Polygon polygon;
      };
    };
  };
};

#endif
