#ifndef __geometry_msgs__msg__Twist__idl__
#define __geometry_msgs__msg__Twist__idl__

#include "geometry_msgs/msg/./Vector3_.idl"
module geometry_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This expresses velocity in free space broken into its linear and angular parts.
       */
      @TypeCode(type="geometry_msgs::msg::dds_::Twist_")
      struct Twist
      {
        geometry_msgs::msg::dds::Vector3 linear;
        geometry_msgs::msg::dds::Vector3 angular;
      };  // struct Twist
    };  // module dds_
  };  // module msg
};  // module geometry_msgs

#endif  // __geometry_msgs__msg__Twist__idl__
