#ifndef __std_msgs__msg__Bool__idl__
#define __std_msgs__msg__Bool__idl__

module std_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="std_msgs::msg::dds_::Bool_")
      struct Bool
      {
        boolean data;
      };
    };
  };
};

#endif
