#ifndef __std_msgs__msg__Byte__idl__
#define __std_msgs__msg__Byte__idl__

module std_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="std_msgs::msg::dds_::Byte_")
      struct Byte
      {
        octet data;
      };
    };
  };
};

#endif
