#ifndef __std_msgs__msg__Char__idl__
#define __std_msgs__msg__Char__idl__

module std_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="std_msgs::msg::dds_::Char_")
      struct Char
      {
        char data;
      };
    };
  };
};

#endif
