#ifndef __std_msgs__msg__Empty__idl__
#define __std_msgs__msg__Empty__idl__

module std_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="std_msgs::msg::dds_::Empty_")
      struct Empty
      {
  boolean _dummy;
      };  // struct Empty
    };  // module dds_
  };  // module msg
};  // module std_msgs

#endif  // __std_msgs__msg__Empty__idl__
