#ifndef __std_msgs__msg__Float32__idl__
#define __std_msgs__msg__Float32__idl__

module std_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="std_msgs::msg::dds_::Float32_")
      struct Float32
      {
        float data;
      };
    };
  };
};

#endif
