#ifndef __std_msgs__msg__Float64__idl__
#define __std_msgs__msg__Float64__idl__

module std_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="std_msgs::msg::dds_::Float64_")
      struct Float64
      {
        double data;
      };
    };
  };
};

#endif
