#ifndef __std_msgs__msg__Header__idl__
#define __std_msgs__msg__Header__idl__

#include "builtin_interfaces/msg/./Time_.idl"
module std_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Standard metadata for higher-level stamped data types.
       * This is generally used to communicate timestamped data
       * in a particular coordinate frame.
       */
      @TypeCode(type="std_msgs::msg::dds_::Header_")
      struct Header
      {
        /**
         * Two-integer timestamp that is expressed as seconds and nanoseconds.
         */
        builtin_interfaces::msg::dds::Time stamp;
        /**
         * Transform frame with which this data is associated.
         */
        string frame_id;
      };  // struct Header
    };  // module dds_
  };  // module msg
};  // module std_msgs

#endif  // __std_msgs__msg__Header__idl__
