#ifndef __std_msgs__msg__Int16__idl__
#define __std_msgs__msg__Int16__idl__

module std_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="std_msgs::msg::dds_::Int16_")
      struct Int16
      {
        short data;
      };  // struct Int16
    };  // module dds_
  };  // module msg
};  // module std_msgs

#endif  // __std_msgs__msg__Int16__idl__
