#ifndef __std_msgs__msg__Int64__idl__
#define __std_msgs__msg__Int64__idl__

module std_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="std_msgs::msg::dds_::Int64_")
      struct Int64
      {
        long long data;
      };
    };
  };
};

#endif
