#ifndef __std_msgs__msg__Int8MultiArray__idl__
#define __std_msgs__msg__Int8MultiArray__idl__

#include "std_msgs/msg/./MultiArrayLayout_.idl"
module std_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Please look at the MultiArrayLayout message definition for
       * documentation on all multiarrays.
       */
      @TypeCode(type="std_msgs::msg::dds_::Int8MultiArray_")
      struct Int8MultiArray
      {
        /**
         * specification of data layout
         */
        std_msgs::msg::dds::MultiArrayLayout layout;
        /**
         * array of data
         */
        sequence<octet> data;
      };  // struct Int8MultiArray
    };  // module dds_
  };  // module msg
};  // module std_msgs

#endif  // __std_msgs__msg__Int8MultiArray__idl__
