#ifndef __actionlib_msgs__msg__GoalStatus__idl__
#define __actionlib_msgs__msg__GoalStatus__idl__

#include "actionlib_msgs/msg/./GoalID_.idl"
module actionlib_msgs
{
  module msg
  {
    module dds
    {
      /**
       * The goal has yet to be processed by the action server.
       */
      const octet PENDING =
      0;

      /**
       * The goal is currently being processed by the action server.
       */
      const octet ACTIVE =
      1;

      /**
       * The goal received a cancel request after it started executing
       */
      const octet PREEMPTED =
      2;

      /**
       * and has since completed its execution (Terminal State).
       * The goal was achieved successfully by the action server
       */
      const octet SUCCEEDED =
      3;

      /**
       * (Terminal State).
       * The goal was aborted during execution by the action server due
       */
      const octet ABORTED =
      4;

      /**
       * to some failure (Terminal State).
       * The goal was rejected by the action server without being processed,
       */
      const octet REJECTED =
      5;

      /**
       * because the goal was unattainable or invalid (Terminal State).
       * The goal received a cancel request after it started executing
       */
      const octet PREEMPTING =
      6;

      /**
       * and has not yet completed execution.
       * The goal received a cancel request before it started executing, but
       */
      const octet RECALLING =
      7;

      /**
       * the action server has not yet confirmed that the goal is canceled.
       * The goal received a cancel request before it started executing
       */
      const octet RECALLED =
      8;

      /**
       * and was successfully cancelled (Terminal State).
       * An action client can determine that a goal is LOST. This should not
       */
      const octet LOST =
      9;


      /**
       * be sent over the wire by an action server.
       */
      @TypeCode(type="actionlib_msgs::msg::dds_::GoalStatus_")
      struct GoalStatus
      {
        actionlib_msgs::msg::dds::GoalID goal_id;
        octet status;
        /**
         * Allow for the user to associate a string with GoalStatus for debugging.
         */
        string text;
      };
    };
  };
};

#endif
