#ifndef __sensor_msgs__msg__LaserScan__idl__
#define __sensor_msgs__msg__LaserScan__idl__

#include "std_msgs/msg/./Header_.idl"
module sensor_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Single scan from a planar laser range-finder
       * 
       * If you have another ranging device with different behavior (e.g. a sonar
       * array), please find or create a different message, since applications
       * will make fairly laser-specific assumptions about this data
       * the first ray in the scan.
       * 
       * in frame frame_id, angles are measured around
       * the positive Z axis (counterclockwise, if Z is up)
       * with zero angle being forward along the x axis
       */
      @TypeCode(type="sensor_msgs::msg::dds_::LaserScan_")
      struct LaserScan
      {
        /**
         * timestamp in the header is the acquisition time of
         */
        std_msgs::msg::dds::Header header;
        /**
         * start angle of the scan [rad]
         */
        float angle_min;
        /**
         * end angle of the scan [rad]
         */
        float angle_max;
        /**
         * angular distance between measurements [rad]
         */
        float angle_increment;
        /**
         * time between measurements [seconds] - if your scanner
         */
        float time_increment;
        /**
         * is moving, this will be used in interpolating position
         * of 3d points
         * time between scans [seconds]
         */
        float scan_time;
        /**
         * minimum range value [m]
         */
        float range_min;
        /**
         * maximum range value [m]
         */
        float range_max;
        /**
         * range data [m]
         */
        sequence<float> ranges;
        /**
         * (Note: values < range_min or > range_max should be discarded)
         * intensity data [device-specific units].  If your
         */
        sequence<float> intensities;
      };  // struct LaserScan
    };  // module dds_
  };  // module msg
};  // module sensor_msgs

#endif  // __sensor_msgs__msg__LaserScan__idl__
