#ifndef __sensor_msgs__msg__PointField__idl__
#define __sensor_msgs__msg__PointField__idl__

module sensor_msgs
{
  module msg
  {
    module dds
    {
      /**
       * This message holds the description of one point entry in the
       * PointCloud2 message format.
       */
      const octet INT8 =
      1;

      const octet UINT8 =
      2;

      const octet INT16 =
      3;

      const octet UINT16 =
      4;

      const octet INT32 =
      5;

      const octet UINT32 =
      6;

      const octet FLOAT32 =
      7;

      const octet FLOAT64 =
      8;


      @TypeCode(type="sensor_msgs::msg::dds_::PointField_")
      struct PointField
      {
        /**
         * Name of field
         */
        string name;
        /**
         * Offset from start of point struct
         */
        unsigned long offset;
        /**
         * Datatype enumeration, see above
         */
        octet datatype;
        /**
         * How many elements in the field
         */
        unsigned long count;
      };
    };
  };
};

#endif
