#ifndef __ros_msgs__msg__CustomBoi__idl__
#define __ros_msgs__msg__CustomBoi__idl__

module ros_msgs
{
    module msg
    {
        module dds
        {
            @TypeCode(type="ros_msgs::msg::dds_::CustomBoi_")
            @Abstract(type="us.ihmc.CustomBoi", impl="new us.ihmc.CustomBoiPubSubTypeImpl()")
            struct CustomBoi
            {
              float x;
              float y;
              float z;
            };
        };
    };
};

#endif
