#ifndef __test_msgs__msg__Builtins__idl__
#define __test_msgs__msg__Builtins__idl__

#include "builtin_interfaces/msg/./Duration_.idl"
#include "builtin_interfaces/msg/./Time_.idl"
module test_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="test_msgs::msg::dds_::Builtins_")
      struct Builtins
      {
        builtin_interfaces::msg::dds::Duration duration_value;
        builtin_interfaces::msg::dds::Time time_value;
      };
    };
  };
};

#endif
