#ifndef __test_msgs__msg__DynamicArrayNested__idl__
#define __test_msgs__msg__DynamicArrayNested__idl__

#include "test_msgs/msg/./Primitives_.idl"
module test_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="test_msgs::msg::dds_::DynamicArrayNested_")
      struct DynamicArrayNested
      {
        sequence<test_msgs::msg::dds::Primitives> primitive_values;
      };
    };
  };
};

#endif
