#ifndef __test_msgs__msg__Empty__idl__
#define __test_msgs__msg__Empty__idl__

module test_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="test_msgs::msg::dds_::Empty_")
      struct Empty
      {
        boolean unused_placeholder_field;
      };
    };
  };
};

#endif
