#ifndef __test_msgs__msg__Nested__idl__
#define __test_msgs__msg__Nested__idl__

#include "test_msgs/msg/./Primitives_.idl"
module test_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="test_msgs::msg::dds_::Nested_")
      struct Nested
      {
        test_msgs::msg::dds::Primitives primitive_values;
      };
    };
  };
};

#endif
