#ifndef __test_msgs__msg__Primitives__idl__
#define __test_msgs__msg__Primitives__idl__

module test_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="test_msgs::msg::dds_::Primitives_")
      struct Primitives
      {
        boolean bool_value;
        octet byte_value;
        char char_value;
        float float32_value;
        double float64_value;
        octet int8_value;
        octet uint8_value;
        short int16_value;
        unsigned short uint16_value;
        long int32_value;
        unsigned long uint32_value;
        long long int64_value;
        unsigned long long uint64_value;
        string string_value;
      };
    };
  };
};

#endif
