#ifndef __test_msgs__msg__StaticArrayPrimitives__idl__
#define __test_msgs__msg__StaticArrayPrimitives__idl__

module test_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="test_msgs::msg::dds_::StaticArrayPrimitives_")
      struct StaticArrayPrimitives
      {
        boolean bool_values[3];
        octet byte_values[3];
        char char_values[3];
        float float32_values[3];
        double float64_values[3];
        octet int8_values[3];
        octet uint8_values[3];
        short int16_values[3];
        unsigned_short uint16_values[3];
        long int32_values[3];
        unsigned_long uint32_values[3];
        long_long int64_values[3];
        unsigned_long_long uint64_values[3];
        string string_values[3];
      };
    };
  };
};

#endif
