# This is the header
# Header line 2
# This is some dangling comment that will be included in header

# a, b, c
# 1, 2, 3
# baby
# sneaky boi
int32 X=123

string CATCH_22="No doc, watch out!"

# this num should have default value 5
# Field default value 5
int64 num

float64 double_test

# I have some doc not relevant to the next
int64 no_default_with_doc

int64 no_doc_num

# @javadoc I guess javadoc will work okay.
# hello
int32 hello


